apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm
  annotations:
    azure.workload.identity/client-id: REPLACE_FROM_PROTECTED_DEPLOYMENT_OUTPUT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      automountServiceAccountToken: false
