model_list: []
router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
general_settings:
  disable_spend_logs: false
  store_prompts_in_spend_logs: false
  maximum_spend_logs_retention_period: 7d
  maximum_spend_logs_retention_interval: 1d
