apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
configMapGenerator:
  - name: litellm-config
    files:
      - config.yaml
    options:
      disableNameSuffixHash: false
labels:
  - pairs:
      app.kubernetes.io/part-of: litellm-gateway
      app.kubernetes.io/managed-by: kustomize
