apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  template:
    spec:
      containers:
        - name: litellm
          env:
            - name: AZURE_CLIENT_ID
              $patch: delete